apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: jh7p9vcae-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:ea1c62db1ec5a0d63f65d21e55999927ecff1c0f@sha256:752549dd2b22e5419fc6fbb2ec564c074915716ff5990df537b0f0448801d43f
          name: container-image
